analyzer:
  exclude: [ build/**, "**.g.dart", "lib/data/models/**" ]
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
    

linter:
  rules:
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    implementation_imports: true
    library_prefixes: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    null_closures: true
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_super_parameters: true
    always_declare_return_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
    no_logic_in_create_state: true
    non_constant_identifier_names: true
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_empty_else: true
    cascade_invocations: true
    implicit_call_tearoffs: true
    prefer_expression_function_bodies: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    camel_case_types: true
    type_annotate_public_apis: true
    avoid_annotating_with_dynamic: true
    avoid_as: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_field_initializers_in_const_classes: true
    avoid_js_rounded_ints: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true